### ISSUE TITLE
setup.py broken

### ISSUE THREAD

**Issue by pitrou** [ContinuumIO/ciocheck#11]
```
$ pip install -e .
Obtaining file:///home/antoine/ciocheck
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/antoine/ciocheck/setup.py", line 44
        description='A stand alone PyQt/PySide GUI application for managing conda '
           ^
    SyntaxError: keyword argument repeated
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /home/antoine/ciocheck/
```

**Comment by goanpeca** [comment]
I guess this is no longer a problem?
